---
# title: role-samba4-primary-ad-dc
#
# Author: bitfinity-nl
# Version: 1.0
# File: tasks/main.yml
#
# Description: Creating a primairy Active Directory Domain Controller.

- name: "For OS: Ubuntu 16.04LTS, Arch: amd64"
  import_tasks: ubuntu-1604-amd64.yml
  when:
    - ansible_distribution_version == "16.04"
    - ansible_architecture == "x86_64"

- name: "Role: primary DC, For OS: Ubuntu 18.04LTS, Arch: amd64"
  import_tasks: ubuntu-1804-amd64.yml
  when:
    - smb_role == "primary"
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"

- name: "Role: additional DC, For OS: Ubuntu 18.04LTS, Arch: amd64"
  import_tasks: ubuntu-1804-amd64.yml
  when:
    - smb_role == "additional"
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"
   
